"""Reads the results.json of all 5 portfolio repositories and generates
a single consolidated HTML dashboard, published via GitHub Pages."""

import json
import os
from datetime import datetime, timezone

REPOS = [
    "calculator-playwright",
    "saucedemo-playwright",
    "restful-booker-restassured",
    "llm-test-case-generator",
    "llm-as-judge",
]

REPO_URLS = {repo: f"https://github.com/sabrinajohanson/{repo}" for repo in REPOS}
ALLURE_URLS = {repo: f"https://sabrinajohanson.github.io/{repo}/" for repo in REPOS}


def load_results():
    results = []
    for repo in REPOS:
        path = os.path.join("results", repo, "results.json")
        with open(path, "r", encoding="utf-8") as f:
            results.append(json.load(f))
    return results


def build_repo_row(r):
    pass_rate = round((r["passed"] / r["total"]) * 100, 1) if r["total"] else 0
    return f"""
    <div class="repo-row" data-open="false">
      <div class="repo-header">
        <span class="repo-name">{r['repo']}</span>
        <span class="repo-summary">
          {r['total']} total, {r['passed']} passed, {r['failed']} failed, {r['skipped']} skipped ({pass_rate}%)
        </span>
      </div>
      <div class="repo-body">
        <p>Duration: {r['duration_seconds']}s</p>
        <p>Last run: {r['timestamp']}</p>
        <p>
          <a href="{REPO_URLS[r['repo']]}" target="_blank">Repository</a> &middot;
          <a href="{ALLURE_URLS[r['repo']]}" target="_blank">Allure Report</a>
        </p>
      </div>
    </div>
    """


def build_dashboard(results):
    total = sum(r["total"] for r in results)
    passed = sum(r["passed"] for r in results)
    failed = sum(r["failed"] for r in results)
    skipped = sum(r["skipped"] for r in results)
    pass_rate = round((passed / total) * 100, 1) if total else 0

    circumference = 345.6
    passed_arc = round((passed / total) * circumference, 1) if total else 0
    failed_arc = round((failed / total) * circumference, 1) if total else 0
    skipped_arc = round((skipped / total) * circumference, 1) if total else 0

    repo_rows = "\n".join(build_repo_row(r) for r in results)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>QA Portfolio - Consolidated Test Dashboard</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #0b0f14; color: #e6edf3; margin: 0; padding: 2rem; }}
  h1 {{ font-weight: 500; font-size: 20px; }}
  .subtitle {{ color: #8b949e; font-size: 13px; margin-top: -8px; }}
  .cards {{ display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 10px; margin: 1.5rem 0; }}
  .card {{ background: #161b22; border-radius: 10px; padding: 0.75rem 1rem; }}
  .card p:first-child {{ font-size: 12px; color: #8b949e; margin: 0 0 4px; }}
  .card p:last-child {{ font-size: 20px; font-weight: 500; margin: 0; }}
  .card.passed {{ background: #0f2a20; }}
  .card.passed p:last-child {{ color: #3fb950; }}
  .card.failed {{ background: #2a1215; }}
  .card.failed p:last-child {{ color: #f85149; }}
  .card.skipped {{ background: #2a230f; }}
  .card.skipped p:last-child {{ color: #d29922; }}
  .chart-box {{ background: #161b22; border-radius: 12px; padding: 1.25rem; display: flex; align-items: center; gap: 2rem; margin-bottom: 1.5rem; }}
  .legend div {{ display: flex; align-items: center; gap: 8px; font-size: 13px; margin-bottom: 8px; }}
  .legend span {{ width: 10px; height: 10px; border-radius: 2px; display: inline-block; }}
  .repo-row {{ border: 0.5px solid #30363d; border-radius: 8px; margin-bottom: 8px; overflow: hidden; }}
  .repo-header {{ display: flex; justify-content: space-between; padding: 10px 14px; cursor: pointer; }}
  .repo-name {{ font-weight: 500; font-size: 13px; }}
  .repo-summary {{ font-size: 12px; color: #8b949e; }}
  .repo-body {{ display: none; padding: 0 14px 12px; font-size: 13px; color: #8b949e; }}
  .repo-body a {{ color: #58a6ff; text-decoration: none; }}
  .footer {{ font-size: 12px; color: #6e7681; margin-top: 1.5rem; }}
</style>
</head>
<body>
  <h1>QA Portfolio - Consolidated Test Dashboard</h1>
  <p class="subtitle">Aggregated results across all 5 repositories, generated by the orchestrator pipeline</p>

  <div class="cards">
    <div class="card"><p>Total</p><p>{total}</p></div>
    <div class="card passed"><p>Passed</p><p>{passed}</p></div>
    <div class="card failed"><p>Failed</p><p>{failed}</p></div>
    <div class="card skipped"><p>Skipped</p><p>{skipped}</p></div>
    <div class="card"><p>Pass rate</p><p>{pass_rate}%</p></div>
  </div>

  <div class="chart-box">
    <svg width="120" height="120" viewBox="0 0 140 140">
      <circle cx="70" cy="70" r="55" fill="none" stroke="#30363d" stroke-width="18"></circle>
      <circle cx="70" cy="70" r="55" fill="none" stroke="#0F6E56" stroke-width="18" stroke-dasharray="{passed_arc} {circumference}" stroke-dashoffset="0" transform="rotate(-90 70 70)"></circle>
      <circle cx="70" cy="70" r="55" fill="none" stroke="#993C1D" stroke-width="18" stroke-dasharray="{failed_arc} {circumference}" stroke-dashoffset="-{passed_arc}" transform="rotate(-90 70 70)"></circle>
      <circle cx="70" cy="70" r="55" fill="none" stroke="#854F0B" stroke-width="18" stroke-dasharray="{skipped_arc} {circumference}" stroke-dashoffset="-{passed_arc + failed_arc}" transform="rotate(-90 70 70)"></circle>
      <text x="70" y="66" text-anchor="middle" style="font-size: 20px; font-weight: 500; fill: #e6edf3;">{pass_rate}%</text>
      <text x="70" y="84" text-anchor="middle" style="font-size: 10px; fill: #8b949e;">pass rate</text>
    </svg>
    <div class="legend">
      <div><span style="background:#0F6E56;"></span>Passed: {passed}</div>
      <div><span style="background:#993C1D;"></span>Failed: {failed}</div>
      <div><span style="background:#854F0B;"></span>Skipped: {skipped}</div>
    </div>
  </div>

  {repo_rows}

  <p class="footer">Generated {generated_at} by qa-portfolio-pipeline</p>

  <script>
    document.querySelectorAll('.repo-row').forEach(function(row) {{
      var header = row.querySelector('.repo-header');
      var body = row.querySelector('.repo-body');
      header.addEventListener('click', function() {{
        var isOpen = row.getAttribute('data-open') === 'true';
        row.setAttribute('data-open', isOpen ? 'false' : 'true');
        body.style.display = isOpen ? 'none' : 'block';
      }});
    }});
  </script>
</body>
</html>"""


def main():
    results = load_results()
    html = build_dashboard(results)

    os.makedirs("dashboard", exist_ok=True)
    with open("dashboard/index.html", "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Consolidated dashboard generated for {len(results)} repositories.")


if __name__ == "__main__":
    main()